In [17]:
import numpy as np
import pandas as pd

In [18]:
dict1={
    'name':['a','b','c','d'],
    'marks':[1,2,3,4],
    'city':['w','x','y','z']
}
df=pd.DataFrame(dict1)
print(df)

  name  marks city
0    a      1    w
1    b      2    x
2    c      3    y
3    d      4    z

In [19]:
df.to_csv('sample.csv')

In [20]:
df.to_csv('sample_index_false.csv',index=False)

In [21]:
df.head(3)

  name  marks city
0    a      1    w
1    b      2    x
2    c      3    y

In [22]:
df.tail(2)

  name  marks city
2    c      3    y
3    d      4    z

In [23]:
df.describe()

          marks
count  4.000000
mean   2.500000
std    1.290994
min    1.000000
25%    1.750000
50%    2.500000
75%    3.250000
max    4.000000

In [24]:
data=pd.read_csv('sample.csv')
data

   Unnamed: 0 name  marks city
0           0    a      1    w
1           1    b      2    x
2           2    c      3    y
3           3    d      4    z

In [25]:
data['marks']

0    1
1    2
2    3
3    4
Name: marks, dtype: int64

In [26]:
data['marks'][0]

np.int64(1)

In [27]:
data['marks'][0]=50

C:\Users\abhin\AppData\Local\Temp\ipykernel_11676\676093518.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['marks'][0]=50

In [28]:
data.to_csv('sample.csv')

In [30]:
data.index=['1st','2nd','3rd','4th']
data

     Unnamed: 0 name  marks city
1st           0    a     50    w
2nd           1    b      2    x
3rd           2    c      3    y
4th           3    d      4    z

### series

In [32]:
ser=pd.Series(np.random.rand(5))
print(ser)
type(ser)

0    0.527221
1    0.310872
2    0.869321
3    0.229239
4    0.996823
dtype: float64

pandas.core.series.Series

### dataframe

In [33]:
newdf=pd.DataFrame(np.random.rand(50,5),index=np.arange(50))
print(newdf)

           0         1         2         3         4
0   0.130124  0.846982  0.187952  0.481218  0.958644
1   0.750724  0.562140  0.150614  0.827114  0.484971
2   0.581918  0.840810  0.706253  0.758133  0.549892
3   0.035024  0.529943  0.268280  0.108281  0.001319
4   0.081774  0.943812  0.384613  0.504389  0.038593
5   0.908502  0.071762  0.442488  0.878295  0.587146
6   0.453450  0.008203  0.816574  0.041049  0.259071
7   0.622178  0.751156  0.322456  0.854526  0.209468
8   0.233405  0.113624  0.450213  0.254841  0.139039
9   0.792317  0.657129  0.441981  0.156557  0.669947
10  0.509574  0.900002  0.837444  0.799247  0.586438
11  0.610112  0.437892  0.718888  0.219451  0.051800
12  0.148436  0.264157  0.548836  0.366745  0.564347
13  0.007292  0.723671  0.575449  0.349024  0.637850
14  0.093757  0.403899  0.685555  0.916128  0.764213
15  0.883905  0.479356  0.823482  0.759141  0.093390
16  0.036545  0.978411  0.171171  0.680639  0.965305
17  0.890322  0.967368  0.852492  0.339800  0.507557
18  0.076852  0.072276  0.876172  0.653519  0.208014
19  0.598382  0.733442  0.120846  0.413644  0.419296
20  0.682031  0.299148  0.474751  0.270810  0.522114
21  0.858029  0.384748  0.878231  0.930600  0.610115
22  0.592169  0.894065  0.830074  0.641674  0.506793
23  0.118766  0.560885  0.302511  0.460100  0.182536
24  0.798322  0.097345  0.712457  0.865464  0.759758
25  0.107913  0.965322  0.402384  0.665148  0.285900
26  0.245168  0.619647  0.648825  0.438239  0.725920
27  0.856991  0.320238  0.048576  0.631860  0.651934
28  0.140071  0.851483  0.327273  0.899778  0.984427
29  0.386777  0.074355  0.383645  0.955439  0.622325
30  0.617671  0.042794  0.072245  0.244415  0.510677
31  0.907434  0.852537  0.829114  0.865108  0.964997
32  0.894901  0.725777  0.442496  0.396796  0.718325
33  0.678244  0.906051  0.471673  0.905719  0.924609
34  0.636793  0.113368  0.675043  0.923768  0.670209
35  0.645840  0.246844  0.484331  0.887717  0.011326
36  0.568221  0.881028  0.017051  0.192774  0.516909
37  0.955382  0.826616  0.332547  0.485594  0.592993
38  0.017388  0.050910  0.693347  0.507801  0.070362
39  0.676929  0.477398  0.969795  0.372270  0.729638
40  0.199573  0.214128  0.100569  0.754236  0.089282
41  0.446594  0.712144  0.263920  0.819811  0.100156
42  0.349339  0.250781  0.239473  0.442280  0.859785
43  0.429990  0.677683  0.312054  0.336101  0.671100
44  0.588845  0.857070  0.120205  0.011972  0.255731
45  0.179274  0.893846  0.750387  0.099010  0.734596
46  0.214620  0.771122  0.381099  0.612220  0.502934
47  0.478409  0.129850  0.480476  0.445492  0.590657
48  0.024377  0.610781  0.552367  0.851759  0.940471
49  0.773486  0.815015  0.155883  0.209855  0.669564

In [34]:
print(type(newdf))

<class 'pandas.core.frame.DataFrame'>

In [35]:
print(newdf.describe())

               0          1          2          3          4
count  50.000000  50.000000  50.000000  50.000000  50.000000
mean    0.470283   0.548180   0.474691   0.549711   0.513449
std     0.304105   0.317288   0.262904   0.280052   0.288968
min     0.007292   0.008203   0.017051   0.011972   0.001319
25%     0.156145   0.254125   0.276838   0.342106   0.256566
50%     0.538898   0.615214   0.446355   0.506095   0.575392
75%     0.681084   0.845439   0.703026   0.825288   0.706519
max     0.955382   0.978411   0.969795   0.955439   0.984427

In [41]:
print(newdf.dtypes)

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [42]:
newdf[0][0]='abhi'

C:\Users\abhin\AppData\Local\Temp\ipykernel_11676\10734758.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]='abhi'
C:\Users\abhin\AppData\Local\Temp\ipykernel_11676\10734758.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'abhi' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]='abhi'

In [43]:
print(newdf.dtypes)

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [44]:
print(newdf.index)

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype='int64')

In [47]:
print(newdf.columns)

RangeIndex(start=0, stop=5, step=1)

In [48]:
print(newdf.to_numpy())

[['abhi' 0.8469817591966146 0.18795225084541434 0.48121797894472074
  0.9586444810459168]
 [0.7507238123615657 0.5621395888124012 0.15061383617402413
  0.8271137396446399 0.48497127057932354]
 [0.5819181151117191 0.8408096078574561 0.706252833343426
  0.7581327950073947 0.549891723907805]
 [0.03502444289935347 0.529943272115616 0.26828003491725305
  0.10828083975610037 0.0013186810334036014]
 [0.08177403966516394 0.9438115823494039 0.38461339313549103
  0.504389018051849 0.038593482786064004]
 [0.9085023744855115 0.07176225524501079 0.4424879437714343
  0.8782950169370437 0.5871464397628164]
 [0.453449524755405 0.008203151814508702 0.8165738086788689
  0.0410489289962408 0.259071069012869]
 [0.6221781843446733 0.7511558132417981 0.3224555374074157
  0.854525605155947 0.2094682318180361]
 [0.23340548553802498 0.11362400064751221 0.4502131850016172
  0.25484125341985364 0.13903898623349997]
 [0.792317011911749 0.6571291957029377 0.4419814440552774
  0.15655674376291995 0.6699474903773488]
 [0.5095742044226453 0.9000020494098733 0.8374437908361164
  0.7992472135004312 0.5864383593054615]
 [0.6101115079456071 0.43789161631055584 0.7188875212262703
  0.21945083528404985 0.05179992155745383]
 [0.14843562051379966 0.26415713746579794 0.5488361789026005
  0.366745051861331 0.5643465912646441]
 [0.007292316414815536 0.7236714245174086 0.575449147333598
  0.34902379453172605 0.6378501385117291]
 [0.09375662740666424 0.40389851174270375 0.6855549724528371
  0.9161282089308233 0.7642125903383032]
 [0.883905407346713 0.4793555784934167 0.8234821365127525
  0.7591413504073526 0.09338961378789357]
 [0.03654468946983014 0.9784107950451918 0.17117076404654796
  0.6806389139635889 0.9653051103323698]
 [0.8903221144419255 0.9673677636142469 0.8524919395915949
  0.3397998607845816 0.5075565042974145]
 [0.07685193963083459 0.0722757383691508 0.8761716141467596
  0.6535193985153843 0.20801426250820143]
 [0.5983820326796323 0.7334424152875871 0.12084557192316414
  0.41364356862754204 0.41929636880490606]
 [0.6820306544841978 0.2991477880291086 0.47475067902215173
  0.27081021180422116 0.5221135593450427]
 [0.8580286091634142 0.3847479833813586 0.8782309233009153
  0.9306002926101828 0.6101154438491294]
 [0.5921693402962431 0.8940649573101919 0.8300744553415701
  0.6416744543800145 0.50679278678675]
 [0.1187659302146663 0.5608851394134577 0.30251067400316745
  0.4601000669133922 0.18253562515726762]
 [0.7983216110359155 0.09734485952342886 0.7124571626914582
  0.865464143995563 0.759758090232939]
 [0.10791275132237554 0.9653217128088799 0.4023839745808889
  0.6651483194461439 0.28589961763960614]
 [0.2451683719044816 0.61964727542271 0.6488250742925518
  0.4382391093185707 0.7259200613847114]
 [0.8569914284185676 0.32023754677350824 0.04857557635481158
  0.6318597081492789 0.6519341917344034]
 [0.14007111204611866 0.8514832247619654 0.3272727348770017
  0.8997781055814874 0.9844266111048137]
 [0.38677709319177844 0.07435473253923919 0.3836445317796775
  0.9554385291959074 0.6223248562719991]
 [0.6176706052045924 0.042793970060779896 0.07224536525006486
  0.2444150116694822 0.5106771097910991]
 [0.9074344221237142 0.8525374142044376 0.8291135391381881
  0.8651077114249287 0.9649965242169862]
 [0.894901130735642 0.725776807720586 0.44249617340641645
  0.3967963435808779 0.7183253482546688]
 [0.6782444241734845 0.9060507417152164 0.4716734614778265
  0.9057185639058054 0.9246091150971169]
 [0.6367931053526048 0.11336819232804796 0.6750430107820353
  0.9237678384058033 0.670208663179771]
 [0.645840097102696 0.24684362248860037 0.48433119312630313
  0.8877166910704875 0.011326109999912903]
 [0.5682208988088353 0.881028304863415 0.017051091926047812
  0.19277383359758304 0.5169094663170731]
 [0.9553823960207483 0.8266157630260044 0.3325473565750495
  0.48559377733285347 0.5929931594784988]
 [0.01738791328100109 0.050909715780703135 0.6933474618842345
  0.5078012851518403 0.07036154163086406]
 [0.6769291582822285 0.4773977126731628 0.9697948342816419
  0.37226975601304524 0.7296378668830533]
 [0.19957349964145676 0.2141284643648258 0.10056856359571664
  0.7542361758850307 0.0892816021648104]
 [0.4465943895570592 0.7121437471644907 0.26392043282733413
  0.819811014564967 0.10015567863301322]
 [0.3493389653930784 0.25078070441331346 0.2394726498800338
  0.4422800722272556 0.8597851084073281]
 [0.4299895059945993 0.6776831064960818 0.3120538167264807
  0.33610081276675474 0.6710995130380459]
 [0.5888453213691186 0.8570695181965343 0.12020481776902803
  0.011972388997078753 0.25573127020315334]
 [0.17927444344766963 0.8938459753935379 0.7503871925203968
  0.0990096431308417 0.7345962376147458]
 [0.21462010150151467 0.7711221785384899 0.3810988737875952
  0.612220046617183 0.5029340692404107]
 [0.4784085628391387 0.12984991414932479 0.4804755238609272
  0.44549175151986486 0.5906565518307736]
 [0.024376705529253084 0.610780715737109 0.5523674077004815
  0.8517592649589921 0.9404713177602495]
 [0.7734858155953245 0.815014974426751 0.15588302470971083
  0.20985522272689305 0.6695644951947968]]

In [49]:
print(newdf.T)

         0         1         2         3         4         5         6   \
0      abhi  0.750724  0.581918  0.035024  0.081774  0.908502   0.45345
1  0.846982   0.56214   0.84081  0.529943  0.943812  0.071762  0.008203
2  0.187952  0.150614  0.706253   0.26828  0.384613  0.442488  0.816574
3  0.481218  0.827114  0.758133  0.108281  0.504389  0.878295  0.041049
4  0.958644  0.484971  0.549892  0.001319  0.038593  0.587146  0.259071

         7         8         9   ...        40        41        42        43  \
0  0.622178  0.233405  0.792317  ...  0.199573  0.446594  0.349339   0.42999
1  0.751156  0.113624  0.657129  ...  0.214128  0.712144  0.250781  0.677683
2  0.322456  0.450213  0.441981  ...  0.100569   0.26392  0.239473  0.312054
3  0.854526  0.254841  0.156557  ...  0.754236  0.819811   0.44228  0.336101
4  0.209468  0.139039  0.669947  ...  0.089282  0.100156  0.859785    0.6711

         44        45        46        47        48        49
0  0.588845  0.179274   0.21462  0.478409  0.024377  0.773486
1   0.85707  0.893846  0.771122   0.12985  0.610781  0.815015
2  0.120205  0.750387  0.381099  0.480476  0.552367  0.155883
3  0.011972   0.09901   0.61222  0.445492  0.851759  0.209855
4  0.255731  0.734596  0.502934  0.590657  0.940471  0.669564

[5 rows x 50 columns]

In [50]:
print(newdf.sort_index(axis=0,ascending=False))

           0         1         2         3         4
49  0.773486  0.815015  0.155883  0.209855  0.669564
48  0.024377  0.610781  0.552367  0.851759  0.940471
47  0.478409  0.129850  0.480476  0.445492  0.590657
46   0.21462  0.771122  0.381099  0.612220  0.502934
45  0.179274  0.893846  0.750387  0.099010  0.734596
44  0.588845  0.857070  0.120205  0.011972  0.255731
43   0.42999  0.677683  0.312054  0.336101  0.671100
42  0.349339  0.250781  0.239473  0.442280  0.859785
41  0.446594  0.712144  0.263920  0.819811  0.100156
40  0.199573  0.214128  0.100569  0.754236  0.089282
39  0.676929  0.477398  0.969795  0.372270  0.729638
38  0.017388  0.050910  0.693347  0.507801  0.070362
37  0.955382  0.826616  0.332547  0.485594  0.592993
36  0.568221  0.881028  0.017051  0.192774  0.516909
35   0.64584  0.246844  0.484331  0.887717  0.011326
34  0.636793  0.113368  0.675043  0.923768  0.670209
33  0.678244  0.906051  0.471673  0.905719  0.924609
32  0.894901  0.725777  0.442496  0.396796  0.718325
31  0.907434  0.852537  0.829114  0.865108  0.964997
30  0.617671  0.042794  0.072245  0.244415  0.510677
29  0.386777  0.074355  0.383645  0.955439  0.622325
28  0.140071  0.851483  0.327273  0.899778  0.984427
27  0.856991  0.320238  0.048576  0.631860  0.651934
26  0.245168  0.619647  0.648825  0.438239  0.725920
25  0.107913  0.965322  0.402384  0.665148  0.285900
24  0.798322  0.097345  0.712457  0.865464  0.759758
23  0.118766  0.560885  0.302511  0.460100  0.182536
22  0.592169  0.894065  0.830074  0.641674  0.506793
21  0.858029  0.384748  0.878231  0.930600  0.610115
20  0.682031  0.299148  0.474751  0.270810  0.522114
19  0.598382  0.733442  0.120846  0.413644  0.419296
18  0.076852  0.072276  0.876172  0.653519  0.208014
17  0.890322  0.967368  0.852492  0.339800  0.507557
16  0.036545  0.978411  0.171171  0.680639  0.965305
15  0.883905  0.479356  0.823482  0.759141  0.093390
14  0.093757  0.403899  0.685555  0.916128  0.764213
13  0.007292  0.723671  0.575449  0.349024  0.637850
12  0.148436  0.264157  0.548836  0.366745  0.564347
11  0.610112  0.437892  0.718888  0.219451  0.051800
10  0.509574  0.900002  0.837444  0.799247  0.586438
9   0.792317  0.657129  0.441981  0.156557  0.669947
8   0.233405  0.113624  0.450213  0.254841  0.139039
7   0.622178  0.751156  0.322456  0.854526  0.209468
6    0.45345  0.008203  0.816574  0.041049  0.259071
5   0.908502  0.071762  0.442488  0.878295  0.587146
4   0.081774  0.943812  0.384613  0.504389  0.038593
3   0.035024  0.529943  0.268280  0.108281  0.001319
2   0.581918  0.840810  0.706253  0.758133  0.549892
1   0.750724  0.562140  0.150614  0.827114  0.484971
0       abhi  0.846982  0.187952  0.481218  0.958644

In [51]:
print(newdf.sort_index(axis=1,ascending=False))

           4         3         2         1         0
0   0.958644  0.481218  0.187952  0.846982      abhi
1   0.484971  0.827114  0.150614  0.562140  0.750724
2   0.549892  0.758133  0.706253  0.840810  0.581918
3   0.001319  0.108281  0.268280  0.529943  0.035024
4   0.038593  0.504389  0.384613  0.943812  0.081774
5   0.587146  0.878295  0.442488  0.071762  0.908502
6   0.259071  0.041049  0.816574  0.008203   0.45345
7   0.209468  0.854526  0.322456  0.751156  0.622178
8   0.139039  0.254841  0.450213  0.113624  0.233405
9   0.669947  0.156557  0.441981  0.657129  0.792317
10  0.586438  0.799247  0.837444  0.900002  0.509574
11  0.051800  0.219451  0.718888  0.437892  0.610112
12  0.564347  0.366745  0.548836  0.264157  0.148436
13  0.637850  0.349024  0.575449  0.723671  0.007292
14  0.764213  0.916128  0.685555  0.403899  0.093757
15  0.093390  0.759141  0.823482  0.479356  0.883905
16  0.965305  0.680639  0.171171  0.978411  0.036545
17  0.507557  0.339800  0.852492  0.967368  0.890322
18  0.208014  0.653519  0.876172  0.072276  0.076852
19  0.419296  0.413644  0.120846  0.733442  0.598382
20  0.522114  0.270810  0.474751  0.299148  0.682031
21  0.610115  0.930600  0.878231  0.384748  0.858029
22  0.506793  0.641674  0.830074  0.894065  0.592169
23  0.182536  0.460100  0.302511  0.560885  0.118766
24  0.759758  0.865464  0.712457  0.097345  0.798322
25  0.285900  0.665148  0.402384  0.965322  0.107913
26  0.725920  0.438239  0.648825  0.619647  0.245168
27  0.651934  0.631860  0.048576  0.320238  0.856991
28  0.984427  0.899778  0.327273  0.851483  0.140071
29  0.622325  0.955439  0.383645  0.074355  0.386777
30  0.510677  0.244415  0.072245  0.042794  0.617671
31  0.964997  0.865108  0.829114  0.852537  0.907434
32  0.718325  0.396796  0.442496  0.725777  0.894901
33  0.924609  0.905719  0.471673  0.906051  0.678244
34  0.670209  0.923768  0.675043  0.113368  0.636793
35  0.011326  0.887717  0.484331  0.246844   0.64584
36  0.516909  0.192774  0.017051  0.881028  0.568221
37  0.592993  0.485594  0.332547  0.826616  0.955382
38  0.070362  0.507801  0.693347  0.050910  0.017388
39  0.729638  0.372270  0.969795  0.477398  0.676929
40  0.089282  0.754236  0.100569  0.214128  0.199573
41  0.100156  0.819811  0.263920  0.712144  0.446594
42  0.859785  0.442280  0.239473  0.250781  0.349339
43  0.671100  0.336101  0.312054  0.677683   0.42999
44  0.255731  0.011972  0.120205  0.857070  0.588845
45  0.734596  0.099010  0.750387  0.893846  0.179274
46  0.502934  0.612220  0.381099  0.771122   0.21462
47  0.590657  0.445492  0.480476  0.129850  0.478409
48  0.940471  0.851759  0.552367  0.610781  0.024377
49  0.669564  0.209855  0.155883  0.815015  0.773486

In [52]:
print(type(newdf[0]))

<class 'pandas.core.series.Series'>

In [53]:
newdf2=newdf
newdf2[0][0]=100
print(newdf)

           0         1         2         3         4
0        100  0.846982  0.187952  0.481218  0.958644
1   0.750724  0.562140  0.150614  0.827114  0.484971
2   0.581918  0.840810  0.706253  0.758133  0.549892
3   0.035024  0.529943  0.268280  0.108281  0.001319
4   0.081774  0.943812  0.384613  0.504389  0.038593
5   0.908502  0.071762  0.442488  0.878295  0.587146
6    0.45345  0.008203  0.816574  0.041049  0.259071
7   0.622178  0.751156  0.322456  0.854526  0.209468
8   0.233405  0.113624  0.450213  0.254841  0.139039
9   0.792317  0.657129  0.441981  0.156557  0.669947
10  0.509574  0.900002  0.837444  0.799247  0.586438
11  0.610112  0.437892  0.718888  0.219451  0.051800
12  0.148436  0.264157  0.548836  0.366745  0.564347
13  0.007292  0.723671  0.575449  0.349024  0.637850
14  0.093757  0.403899  0.685555  0.916128  0.764213
15  0.883905  0.479356  0.823482  0.759141  0.093390
16  0.036545  0.978411  0.171171  0.680639  0.965305
17  0.890322  0.967368  0.852492  0.339800  0.507557
18  0.076852  0.072276  0.876172  0.653519  0.208014
19  0.598382  0.733442  0.120846  0.413644  0.419296
20  0.682031  0.299148  0.474751  0.270810  0.522114
21  0.858029  0.384748  0.878231  0.930600  0.610115
22  0.592169  0.894065  0.830074  0.641674  0.506793
23  0.118766  0.560885  0.302511  0.460100  0.182536
24  0.798322  0.097345  0.712457  0.865464  0.759758
25  0.107913  0.965322  0.402384  0.665148  0.285900
26  0.245168  0.619647  0.648825  0.438239  0.725920
27  0.856991  0.320238  0.048576  0.631860  0.651934
28  0.140071  0.851483  0.327273  0.899778  0.984427
29  0.386777  0.074355  0.383645  0.955439  0.622325
30  0.617671  0.042794  0.072245  0.244415  0.510677
31  0.907434  0.852537  0.829114  0.865108  0.964997
32  0.894901  0.725777  0.442496  0.396796  0.718325
33  0.678244  0.906051  0.471673  0.905719  0.924609
34  0.636793  0.113368  0.675043  0.923768  0.670209
35   0.64584  0.246844  0.484331  0.887717  0.011326
36  0.568221  0.881028  0.017051  0.192774  0.516909
37  0.955382  0.826616  0.332547  0.485594  0.592993
38  0.017388  0.050910  0.693347  0.507801  0.070362
39  0.676929  0.477398  0.969795  0.372270  0.729638
40  0.199573  0.214128  0.100569  0.754236  0.089282
41  0.446594  0.712144  0.263920  0.819811  0.100156
42  0.349339  0.250781  0.239473  0.442280  0.859785
43   0.42999  0.677683  0.312054  0.336101  0.671100
44  0.588845  0.857070  0.120205  0.011972  0.255731
45  0.179274  0.893846  0.750387  0.099010  0.734596
46   0.21462  0.771122  0.381099  0.612220  0.502934
47  0.478409  0.129850  0.480476  0.445492  0.590657
48  0.024377  0.610781  0.552367  0.851759  0.940471
49  0.773486  0.815015  0.155883  0.209855  0.669564

In [55]:
newdf2=newdf.copy()
newdf2[0][0]=200
print(newdf)

           0         1         2         3         4
0        100  0.846982  0.187952  0.481218  0.958644
1   0.750724  0.562140  0.150614  0.827114  0.484971
2   0.581918  0.840810  0.706253  0.758133  0.549892
3   0.035024  0.529943  0.268280  0.108281  0.001319
4   0.081774  0.943812  0.384613  0.504389  0.038593
5   0.908502  0.071762  0.442488  0.878295  0.587146
6    0.45345  0.008203  0.816574  0.041049  0.259071
7   0.622178  0.751156  0.322456  0.854526  0.209468
8   0.233405  0.113624  0.450213  0.254841  0.139039
9   0.792317  0.657129  0.441981  0.156557  0.669947
10  0.509574  0.900002  0.837444  0.799247  0.586438
11  0.610112  0.437892  0.718888  0.219451  0.051800
12  0.148436  0.264157  0.548836  0.366745  0.564347
13  0.007292  0.723671  0.575449  0.349024  0.637850
14  0.093757  0.403899  0.685555  0.916128  0.764213
15  0.883905  0.479356  0.823482  0.759141  0.093390
16  0.036545  0.978411  0.171171  0.680639  0.965305
17  0.890322  0.967368  0.852492  0.339800  0.507557
18  0.076852  0.072276  0.876172  0.653519  0.208014
19  0.598382  0.733442  0.120846  0.413644  0.419296
20  0.682031  0.299148  0.474751  0.270810  0.522114
21  0.858029  0.384748  0.878231  0.930600  0.610115
22  0.592169  0.894065  0.830074  0.641674  0.506793
23  0.118766  0.560885  0.302511  0.460100  0.182536
24  0.798322  0.097345  0.712457  0.865464  0.759758
25  0.107913  0.965322  0.402384  0.665148  0.285900
26  0.245168  0.619647  0.648825  0.438239  0.725920
27  0.856991  0.320238  0.048576  0.631860  0.651934
28  0.140071  0.851483  0.327273  0.899778  0.984427
29  0.386777  0.074355  0.383645  0.955439  0.622325
30  0.617671  0.042794  0.072245  0.244415  0.510677
31  0.907434  0.852537  0.829114  0.865108  0.964997
32  0.894901  0.725777  0.442496  0.396796  0.718325
33  0.678244  0.906051  0.471673  0.905719  0.924609
34  0.636793  0.113368  0.675043  0.923768  0.670209
35   0.64584  0.246844  0.484331  0.887717  0.011326
36  0.568221  0.881028  0.017051  0.192774  0.516909
37  0.955382  0.826616  0.332547  0.485594  0.592993
38  0.017388  0.050910  0.693347  0.507801  0.070362
39  0.676929  0.477398  0.969795  0.372270  0.729638
40  0.199573  0.214128  0.100569  0.754236  0.089282
41  0.446594  0.712144  0.263920  0.819811  0.100156
42  0.349339  0.250781  0.239473  0.442280  0.859785
43   0.42999  0.677683  0.312054  0.336101  0.671100
44  0.588845  0.857070  0.120205  0.011972  0.255731
45  0.179274  0.893846  0.750387  0.099010  0.734596
46   0.21462  0.771122  0.381099  0.612220  0.502934
47  0.478409  0.129850  0.480476  0.445492  0.590657
48  0.024377  0.610781  0.552367  0.851759  0.940471
49  0.773486  0.815015  0.155883  0.209855  0.669564

C:\Users\abhin\AppData\Local\Temp\ipykernel_11676\2898292060.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]=200
C:\Users\abhin\AppData\Local\Temp\ipykernel_11676\2898292060.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]=200

In [66]:
newdf.loc[0,0]=300
newdf.head(2)

          A         B         C         D         E      0
0       300  0.846982  0.187952  0.481218  0.958644  300.0
1  0.750724  0.562140  0.150614  0.827114  0.484971    NaN

In [67]:
newdf.loc[0,0]=500
newdf.head()

          A         B         C         D         E      0
0       300  0.846982  0.187952  0.481218  0.958644  500.0
1  0.750724  0.562140  0.150614  0.827114  0.484971    NaN
2  0.581918  0.840810  0.706253  0.758133  0.549892    NaN
3  0.035024  0.529943  0.268280  0.108281  0.001319    NaN
4  0.081774  0.943812  0.384613  0.504389  0.038593    NaN

In [70]:
newdf[0,'A']=400
newdf.head()

          A         B         C         D         E      0  (0, A)
0       300  0.846982  0.187952  0.481218  0.958644  500.0     400
1  0.750724  0.562140  0.150614  0.827114  0.484971    NaN     400
2  0.581918  0.840810  0.706253  0.758133  0.549892    NaN     400
3  0.035024  0.529943  0.268280  0.108281  0.001319    NaN     400
4  0.081774  0.943812  0.384613  0.504389  0.038593    NaN     400

In [71]:
# to drop any column
newdf.drop(0,axis=1)
newdf.head()

          A         B         C         D         E      0  (0, A)
0       300  0.846982  0.187952  0.481218  0.958644  500.0     400
1  0.750724  0.562140  0.150614  0.827114  0.484971    NaN     400
2  0.581918  0.840810  0.706253  0.758133  0.549892    NaN     400
3  0.035024  0.529943  0.268280  0.108281  0.001319    NaN     400
4  0.081774  0.943812  0.384613  0.504389  0.038593    NaN     400

In [74]:
newdf.drop(0)
newdf.head()

          A         B         C         D         E      0  (0, A)
0       300  0.846982  0.187952  0.481218  0.958644  500.0     400
1  0.750724  0.562140  0.150614  0.827114  0.484971    NaN     400
2  0.581918  0.840810  0.706253  0.758133  0.549892    NaN     400
3  0.035024  0.529943  0.268280  0.108281  0.001319    NaN     400
4  0.081774  0.943812  0.384613  0.504389  0.038593    NaN     400

In [75]:
newdf.loc[[1,2],['C']]

          C
1  0.150614
2  0.706253

In [76]:
newdf.loc[[1,2],:]

          A        B         C         D         E   0  (0, A)
1  0.750724  0.56214  0.150614  0.827114  0.484971 NaN     400
2  0.581918  0.84081  0.706253  0.758133  0.549892 NaN     400

In [77]:
newdf.loc[:,['C','D']]

           C         D
0   0.187952  0.481218
1   0.150614  0.827114
2   0.706253  0.758133
3   0.268280  0.108281
4   0.384613  0.504389
5   0.442488  0.878295
6   0.816574  0.041049
7   0.322456  0.854526
8   0.450213  0.254841
9   0.441981  0.156557
10  0.837444  0.799247
11  0.718888  0.219451
12  0.548836  0.366745
13  0.575449  0.349024
14  0.685555  0.916128
15  0.823482  0.759141
16  0.171171  0.680639
17  0.852492  0.339800
18  0.876172  0.653519
19  0.120846  0.413644
20  0.474751  0.270810
21  0.878231  0.930600
22  0.830074  0.641674
23  0.302511  0.460100
24  0.712457  0.865464
25  0.402384  0.665148
26  0.648825  0.438239
27  0.048576  0.631860
28  0.327273  0.899778
29  0.383645  0.955439
30  0.072245  0.244415
31  0.829114  0.865108
32  0.442496  0.396796
33  0.471673  0.905719
34  0.675043  0.923768
35  0.484331  0.887717
36  0.017051  0.192774
37  0.332547  0.485594
38  0.693347  0.507801
39  0.969795  0.372270
40  0.100569  0.754236
41  0.263920  0.819811
42  0.239473  0.442280
43  0.312054  0.336101
44  0.120205  0.011972
45  0.750387  0.099010
46  0.381099  0.612220
47  0.480476  0.445492
48  0.552367  0.851759
49  0.155883  0.209855

In [78]:
newdf.loc[(newdf['A']<0.3)]

           A         B         C         D         E   0  (0, A)
3   0.035024  0.529943  0.268280  0.108281  0.001319 NaN     400
4   0.081774  0.943812  0.384613  0.504389  0.038593 NaN     400
8   0.233405  0.113624  0.450213  0.254841  0.139039 NaN     400
12  0.148436  0.264157  0.548836  0.366745  0.564347 NaN     400
13  0.007292  0.723671  0.575449  0.349024  0.637850 NaN     400
14  0.093757  0.403899  0.685555  0.916128  0.764213 NaN     400
16  0.036545  0.978411  0.171171  0.680639  0.965305 NaN     400
18  0.076852  0.072276  0.876172  0.653519  0.208014 NaN     400
23  0.118766  0.560885  0.302511  0.460100  0.182536 NaN     400
25  0.107913  0.965322  0.402384  0.665148  0.285900 NaN     400
26  0.245168  0.619647  0.648825  0.438239  0.725920 NaN     400
28  0.140071  0.851483  0.327273  0.899778  0.984427 NaN     400
38  0.017388  0.050910  0.693347  0.507801  0.070362 NaN     400
40  0.199573  0.214128  0.100569  0.754236  0.089282 NaN     400
45  0.179274  0.893846  0.750387  0.099010  0.734596 NaN     400
46   0.21462  0.771122  0.381099  0.612220  0.502934 NaN     400
48  0.024377  0.610781  0.552367  0.851759  0.940471 NaN     400

In [79]:
newdf.loc[(newdf['A']<0.3)&(newdf['C']>0.5)]

           A         B         C         D         E   0  (0, A)
12  0.148436  0.264157  0.548836  0.366745  0.564347 NaN     400
13  0.007292  0.723671  0.575449  0.349024  0.637850 NaN     400
14  0.093757  0.403899  0.685555  0.916128  0.764213 NaN     400
18  0.076852  0.072276  0.876172  0.653519  0.208014 NaN     400
26  0.245168  0.619647  0.648825  0.438239  0.725920 NaN     400
38  0.017388  0.050910  0.693347  0.507801  0.070362 NaN     400
45  0.179274  0.893846  0.750387  0.099010  0.734596 NaN     400
48  0.024377  0.610781  0.552367  0.851759  0.940471 NaN     400

In [80]:
newdf.iloc[0,4]

np.float64(0.9586444810459168)

In [81]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.846982  0.187952
1  0.562140  0.150614

In [82]:
newdf.drop([0])

           A         B         C         D         E   0  (0, A)
1   0.750724  0.562140  0.150614  0.827114  0.484971 NaN     400
2   0.581918  0.840810  0.706253  0.758133  0.549892 NaN     400
3   0.035024  0.529943  0.268280  0.108281  0.001319 NaN     400
4   0.081774  0.943812  0.384613  0.504389  0.038593 NaN     400
5   0.908502  0.071762  0.442488  0.878295  0.587146 NaN     400
6    0.45345  0.008203  0.816574  0.041049  0.259071 NaN     400
7   0.622178  0.751156  0.322456  0.854526  0.209468 NaN     400
8   0.233405  0.113624  0.450213  0.254841  0.139039 NaN     400
9   0.792317  0.657129  0.441981  0.156557  0.669947 NaN     400
10  0.509574  0.900002  0.837444  0.799247  0.586438 NaN     400
11  0.610112  0.437892  0.718888  0.219451  0.051800 NaN     400
12  0.148436  0.264157  0.548836  0.366745  0.564347 NaN     400
13  0.007292  0.723671  0.575449  0.349024  0.637850 NaN     400
14  0.093757  0.403899  0.685555  0.916128  0.764213 NaN     400
15  0.883905  0.479356  0.823482  0.759141  0.093390 NaN     400
16  0.036545  0.978411  0.171171  0.680639  0.965305 NaN     400
17  0.890322  0.967368  0.852492  0.339800  0.507557 NaN     400
18  0.076852  0.072276  0.876172  0.653519  0.208014 NaN     400
19  0.598382  0.733442  0.120846  0.413644  0.419296 NaN     400
20  0.682031  0.299148  0.474751  0.270810  0.522114 NaN     400
21  0.858029  0.384748  0.878231  0.930600  0.610115 NaN     400
22  0.592169  0.894065  0.830074  0.641674  0.506793 NaN     400
23  0.118766  0.560885  0.302511  0.460100  0.182536 NaN     400
24  0.798322  0.097345  0.712457  0.865464  0.759758 NaN     400
25  0.107913  0.965322  0.402384  0.665148  0.285900 NaN     400
26  0.245168  0.619647  0.648825  0.438239  0.725920 NaN     400
27  0.856991  0.320238  0.048576  0.631860  0.651934 NaN     400
28  0.140071  0.851483  0.327273  0.899778  0.984427 NaN     400
29  0.386777  0.074355  0.383645  0.955439  0.622325 NaN     400
30  0.617671  0.042794  0.072245  0.244415  0.510677 NaN     400
31  0.907434  0.852537  0.829114  0.865108  0.964997 NaN     400
32  0.894901  0.725777  0.442496  0.396796  0.718325 NaN     400
33  0.678244  0.906051  0.471673  0.905719  0.924609 NaN     400
34  0.636793  0.113368  0.675043  0.923768  0.670209 NaN     400
35   0.64584  0.246844  0.484331  0.887717  0.011326 NaN     400
36  0.568221  0.881028  0.017051  0.192774  0.516909 NaN     400
37  0.955382  0.826616  0.332547  0.485594  0.592993 NaN     400
38  0.017388  0.050910  0.693347  0.507801  0.070362 NaN     400
39  0.676929  0.477398  0.969795  0.372270  0.729638 NaN     400
40  0.199573  0.214128  0.100569  0.754236  0.089282 NaN     400
41  0.446594  0.712144  0.263920  0.819811  0.100156 NaN     400
42  0.349339  0.250781  0.239473  0.442280  0.859785 NaN     400
43   0.42999  0.677683  0.312054  0.336101  0.671100 NaN     400
44  0.588845  0.857070  0.120205  0.011972  0.255731 NaN     400
45  0.179274  0.893846  0.750387  0.099010  0.734596 NaN     400
46   0.21462  0.771122  0.381099  0.612220  0.502934 NaN     400
47  0.478409  0.129850  0.480476  0.445492  0.590657 NaN     400
48  0.024377  0.610781  0.552367  0.851759  0.940471 NaN     400
49  0.773486  0.815015  0.155883  0.209855  0.669564 NaN     400

In [83]:
newdf.drop(['A'],axis=1)

           B         C         D         E      0  (0, A)
0   0.846982  0.187952  0.481218  0.958644  500.0     400
1   0.562140  0.150614  0.827114  0.484971    NaN     400
2   0.840810  0.706253  0.758133  0.549892    NaN     400
3   0.529943  0.268280  0.108281  0.001319    NaN     400
4   0.943812  0.384613  0.504389  0.038593    NaN     400
5   0.071762  0.442488  0.878295  0.587146    NaN     400
6   0.008203  0.816574  0.041049  0.259071    NaN     400
7   0.751156  0.322456  0.854526  0.209468    NaN     400
8   0.113624  0.450213  0.254841  0.139039    NaN     400
9   0.657129  0.441981  0.156557  0.669947    NaN     400
10  0.900002  0.837444  0.799247  0.586438    NaN     400
11  0.437892  0.718888  0.219451  0.051800    NaN     400
12  0.264157  0.548836  0.366745  0.564347    NaN     400
13  0.723671  0.575449  0.349024  0.637850    NaN     400
14  0.403899  0.685555  0.916128  0.764213    NaN     400
15  0.479356  0.823482  0.759141  0.093390    NaN     400
16  0.978411  0.171171  0.680639  0.965305    NaN     400
17  0.967368  0.852492  0.339800  0.507557    NaN     400
18  0.072276  0.876172  0.653519  0.208014    NaN     400
19  0.733442  0.120846  0.413644  0.419296    NaN     400
20  0.299148  0.474751  0.270810  0.522114    NaN     400
21  0.384748  0.878231  0.930600  0.610115    NaN     400
22  0.894065  0.830074  0.641674  0.506793    NaN     400
23  0.560885  0.302511  0.460100  0.182536    NaN     400
24  0.097345  0.712457  0.865464  0.759758    NaN     400
25  0.965322  0.402384  0.665148  0.285900    NaN     400
26  0.619647  0.648825  0.438239  0.725920    NaN     400
27  0.320238  0.048576  0.631860  0.651934    NaN     400
28  0.851483  0.327273  0.899778  0.984427    NaN     400
29  0.074355  0.383645  0.955439  0.622325    NaN     400
30  0.042794  0.072245  0.244415  0.510677    NaN     400
31  0.852537  0.829114  0.865108  0.964997    NaN     400
32  0.725777  0.442496  0.396796  0.718325    NaN     400
33  0.906051  0.471673  0.905719  0.924609    NaN     400
34  0.113368  0.675043  0.923768  0.670209    NaN     400
35  0.246844  0.484331  0.887717  0.011326    NaN     400
36  0.881028  0.017051  0.192774  0.516909    NaN     400
37  0.826616  0.332547  0.485594  0.592993    NaN     400
38  0.050910  0.693347  0.507801  0.070362    NaN     400
39  0.477398  0.969795  0.372270  0.729638    NaN     400
40  0.214128  0.100569  0.754236  0.089282    NaN     400
41  0.712144  0.263920  0.819811  0.100156    NaN     400
42  0.250781  0.239473  0.442280  0.859785    NaN     400
43  0.677683  0.312054  0.336101  0.671100    NaN     400
44  0.857070  0.120205  0.011972  0.255731    NaN     400
45  0.893846  0.750387  0.099010  0.734596    NaN     400
46  0.771122  0.381099  0.612220  0.502934    NaN     400
47  0.129850  0.480476  0.445492  0.590657    NaN     400
48  0.610781  0.552367  0.851759  0.940471    NaN     400
49  0.815015  0.155883  0.209855  0.669564    NaN     400

In [84]:
newdf=newdf.drop(['A'],axis=1)

In [85]:
newdf.head()

          B         C         D         E      0  (0, A)
0  0.846982  0.187952  0.481218  0.958644  500.0     400
1  0.562140  0.150614  0.827114  0.484971    NaN     400
2  0.840810  0.706253  0.758133  0.549892    NaN     400
3  0.529943  0.268280  0.108281  0.001319    NaN     400
4  0.943812  0.384613  0.504389  0.038593    NaN     400

In [88]:
newdf.drop(['B','D'],axis=1,inplace=True)
newdf.head()

          C         E      0  (0, A)
0  0.187952  0.958644  500.0     400
1  0.150614  0.484971    NaN     400
2  0.706253  0.549892    NaN     400
3  0.268280  0.001319    NaN     400
4  0.384613  0.038593    NaN     400

In [89]:
newdf.drop([1,5],axis=0,inplace=True)
newdf.head()

          C         E      0  (0, A)
0  0.187952  0.958644  500.0     400
2  0.706253  0.549892    NaN     400
3  0.268280  0.001319    NaN     400
4  0.384613  0.038593    NaN     400
6  0.816574  0.259071    NaN     400

In [90]:
# Create DataFrame
data = {
    'A': [10, 20, 30],
    'B': [5, 15, 25]
}

df = pd.DataFrame(data)

# Methods
print("Describe:\n", df.describe())
print("\nMean:\n", df.mean())
print("\nCorrelation:\n", df.corr())
print("\nCount:\n", df.count())
print("\nMin:\n", df.min())
print("\nMax:\n", df.max())
print("\nMedian:\n", df.median())
print("\nStandard Deviation:\n", df.std())

Describe:
           A     B
count   3.0   3.0
mean   20.0  15.0
std    10.0  10.0
min    10.0   5.0
25%    15.0  10.0
50%    20.0  15.0
75%    25.0  20.0
max    30.0  25.0

Mean:
 A    20.0
B    15.0
dtype: float64

Correlation:
      A    B
A  1.0  1.0
B  1.0  1.0

Count:
 A    3
B    3
dtype: int64

Min:
 A    10
B     5
dtype: int64

Max:
 A    30
B    25
dtype: int64

Median:
 A    20.0
B    15.0
dtype: float64

Standard Deviation:
 A    10.0
B    10.0
dtype: float64